const surahs = {
  "1": {
    "arabic": "الفاتحة",
    "latin": "Al-Fatiha",
    "english": "The Opening",
    "location": 1,
    "sajda": 0,
    "ayah": 7,
  },
  "2": {
    "arabic": "البقرة",
    "latin": "Al-Baqara",
    "english": "The Cow",
    "location": 2,
    "sajda": 0,
    "ayah": 286,
  },
  "3": {
    "arabic": "آل عمران",
    "latin": "Aal-e-Imran",
    "english": "The Family of Imran",
    "location": 2,
    "sajda": 0,
    "ayah": 200,
  },
  "4": {
    "arabic": "النساء",
    "latin": "An-Nisa",
    "english": "The Women",
    "location": 2,
    "sajda": 0,
    "ayah": 176,
  },
  "5": {
    "arabic": "المائدة",
    "latin": "Al-Maeda",
    "english": "The Table Spread",
    "location": 2,
    "sajda": 0,
    "ayah": 120,
  },
  "6": {
    "arabic": "الأنعام",
    "latin": "Al-Anaam",
    "english": "The Cattle",
    "location": 1,
    "sajda": 0,
    "ayah": 165,
  },
  "7": {
    "arabic": "الأعراف",
    "latin": "Al-Araf",
    "english": "The heights",
    "location": 1,
    "sajda": 206,
    "ayah": 206,
  },
  "8": {
    "arabic": "الأنفال",
    "latin": "Al-Anfal",
    "english": "Spoils of war",
    "location": "booty",
    "sajda": 2,
    "ayah": 75,
  },
  "9": {
    "arabic": "التوبة",
    "latin": "At-Taubah",
    "english": "Repentance",
    "location": 2,
    "sajda": 0,
    "ayah": 129,
  },
  "10": {
    "arabic": "يونس",
    "latin": "Yunus",
    "english": "Jonah",
    "location": 1,
    "sajda": 0,
    "ayah": 109,
  },
  "11": {
    "arabic": "هود",
    "latin": "Hud",
    "english": "Hud",
    "location": 1,
    "sajda": 0,
    "ayah": 123,
  },
  "12": {
    "arabic": "يوسف",
    "latin": "Yusuf",
    "english": "Joseph",
    "location": 1,
    "sajda": 0,
    "ayah": 111,
  },
  "13": {
    "arabic": "الرعد",
    "latin": "Ar-Rad",
    "english": "The Thunder",
    "location": 1,
    "sajda": 15,
    "ayah": 43,
  },
  "14": {
    "arabic": "إبراهيم",
    "latin": "Ibrahim",
    "english": "Abraham",
    "location": 1,
    "sajda": 0,
    "ayah": 52,
  },
  "15": {
    "arabic": "الحجر",
    "latin": "Al-Hijr",
    "english": "Stoneland",
    "location": "Rock city",
    "sajda": "Al-Hijr valley",
    "ayah": 99,
  },
  "16": {
    "arabic": "النحل",
    "latin": "An-Nahl",
    "english": "The Bee",
    "location": 1,
    "sajda": 50,
    "ayah": 128,
  },
  "17": {
    "arabic": "الإسراء",
    "latin": "Al-Isra",
    "english": "The Night Journey",
    "location": 1,
    "sajda": 100,
    "ayah": 111,
  },
  "18": {
    "arabic": "الكهف",
    "latin": "Al-Kahf",
    "english": "The Cave",
    "location": 1,
    "sajda": 0,
    "ayah": 110,
  },
  "19": {
    "arabic": "مريم",
    "latin": "Maryam",
    "english": "Mary",
    "location": 1,
    "sajda": 58,
    "ayah": 98,
  },
  "20": {
    "arabic": "طه",
    "latin": "Taha",
    "english": "Taha",
    "location": 1,
    "sajda": 0,
    "ayah": 135,
  },
  "21": {
    "arabic": "الأنبياء",
    "latin": "Al-Anbiya",
    "english": "The Prophets",
    "location": 1,
    "sajda": 0,
    "ayah": 112,
  },
  "22": {
    "arabic": "الحج",
    "latin": "Al-Hajj",
    "english": "The Pilgrimage",
    "location": 1,
    "sajda": 18,
    "ayah": 78,
  },
  "23": {
    "arabic": "المؤمنون",
    "latin": "Al-Mumenoon",
    "english": "The Believers",
    "location": 1,
    "sajda": 0,
    "ayah": 118,
  },
  "24": {
    "arabic": "النور",
    "latin": "An-Noor",
    "english": "The Light",
    "location": 1,
    "sajda": 0,
    "ayah": 64,
  },
  "25": {
    "arabic": "الفرقان",
    "latin": "Al-Furqan",
    "english": "The Standard",
    "location": 1,
    "sajda": 60,
    "ayah": 77,
  },
  "26": {
    "arabic": "الشعراء",
    "latin": "Ash-Shuara",
    "english": "The Poets",
    "location": 1,
    "sajda": 0,
    "ayah": 227,
  },
  "27": {
    "arabic": "النمل",
    "latin": "An-Naml",
    "english": "The Ant",
    "location": 1,
    "sajda": 26,
    "ayah": 93,
  },
  "28": {
    "arabic": "القصص",
    "latin": "Al-Qasas",
    "english": "The Story",
    "location": 1,
    "sajda": 0,
    "ayah": 88,
  },
  "29": {
    "arabic": "العنكبوت",
    "latin": "Al-Ankaboot",
    "english": "The Spider",
    "location": 1,
    "sajda": 0,
    "ayah": 69,
  },
  "30": {
    "arabic": "الروم",
    "latin": "Ar-Room",
    "english": "The Romans",
    "location": 1,
    "sajda": 0,
    "ayah": 60,
  },
  "31": {
    "arabic": "لقمان",
    "latin": "Luqman",
    "english": "Luqman",
    "location": 1,
    "sajda": 0,
    "ayah": 34,
  },
  "32": {
    "arabic": "السجدة",
    "latin": "As-Sajda",
    "english": "The Prostration",
    "location": 1,
    "sajda": 15,
    "ayah": 30,
  },
  "33": {
    "arabic": "الأحزاب",
    "latin": "Al-Ahzab",
    "english": "The Coalition",
    "location": 1,
    "sajda": 0,
    "ayah": 73,
  },
  "34": {
    "arabic": "سبأ",
    "latin": "Saba",
    "english": "Saba",
    "location": 1,
    "sajda": 0,
    "ayah": 54,
  },
  "35": {
    "arabic": "فاطر",
    "latin": "Fatir",
    "english": "Originator",
    "location": 1,
    "sajda": 0,
    "ayah": 45,
  },
  "36": {
    "arabic": "يس",
    "latin": "Ya Seen",
    "english": "Ya Seen",
    "location": 1,
    "sajda": 0,
    "ayah": 83,
  },
  "37": {
    "arabic": "الصافات",
    "latin": "As-Saaffat",
    "english": "Those Who Set The Ranks",
    "location": 1,
    "sajda": 0,
    "ayah": 182,
  },
  "38": {
    "arabic": "ص",
    "latin": "Sad",
    "english": "Sad",
    "location": 1,
    "sajda": 24,
    "ayah": 88,
  },
  "39": {
    "arabic": "الزمر",
    "latin": "Az-Zumar",
    "english": "The Troops",
    "location": 1,
    "sajda": 0,
    "ayah": 75,
  },
  "40": {
    "arabic": "غافر",
    "latin": "Ghafir",
    "english": "The Forgiver",
    "location": 1,
    "sajda": 0,
    "ayah": 85,
  },
  "41": {
    "arabic": "فصلت",
    "latin": "Fussilat",
    "english": "Explained in detail",
    "location": 1,
    "sajda": 38,
    "ayah": 54,
  },
  "42": {
    "arabic": "الشورى",
    "latin": "Ash-Shura",
    "english": "Council",
    "location": "Consultation",
    "sajda": 1,
    "ayah": 53,
  },
  "43": {
    "arabic": "الزخرف",
    "latin": "Az-Zukhruf",
    "english": "Ornaments of Gold",
    "location": 1,
    "sajda": 0,
    "ayah": 89,
  },
  "44": {
    "arabic": "الدخان",
    "latin": "Ad-Dukhan",
    "english": "The Smoke",
    "location": 1,
    "sajda": 0,
    "ayah": 59,
  },
  "45": {
    "arabic": "الجاثية",
    "latin": "Al-Jathiya",
    "english": "Crouching",
    "location": 1,
    "sajda": 0,
    "ayah": 37,
  },
  "46": {
    "arabic": "الأحقاف",
    "latin": "Al-Ahqaf",
    "english": "The Wind-Curved Sandhills",
    "location": 1,
    "sajda": 0,
    "ayah": 35,
  },
  "47": {
    "arabic": "محمد",
    "latin": "Muhammad",
    "english": "Muhammad",
    "location": 2,
    "sajda": 0,
    "ayah": 38,
  },
  "48": {
    "arabic": "الفتح",
    "latin": "Al-Fath",
    "english": "The Victory",
    "location": 2,
    "sajda": 0,
    "ayah": 29,
  },
  "49": {
    "arabic": "الحجرات",
    "latin": "Al-Hujraat",
    "english": "The Private Apartments",
    "location": 2,
    "sajda": 0,
    "ayah": 18,
  },
  "50": {
    "arabic": "ق",
    "latin": "Qaf",
    "english": "Qaf",
    "location": 1,
    "sajda": 0,
    "ayah": 45,
  },
  "51": {
    "arabic": "الذاريات",
    "latin": "Adh-Dhariyat",
    "english": "The Winnowing Winds",
    "location": 1,
    "sajda": 0,
    "ayah": 60,
  },
  "52": {
    "arabic": "الطور",
    "latin": "At-tur",
    "english": "Mount Sinai",
    "location": 1,
    "sajda": 0,
    "ayah": 49,
  },
  "53": {
    "arabic": "النجم",
    "latin": "An-Najm",
    "english": "The Star",
    "location": 1,
    "sajda": 62,
    "ayah": 62,
  },
  "54": {
    "arabic": "القمر",
    "latin": "Al-Qamar",
    "english": "The moon",
    "location": 1,
    "sajda": 0,
    "ayah": 55,
  },
  "55": {
    "arabic": "الرحمن",
    "latin": "Al-Rahman",
    "english": "The Beneficient",
    "location": 1,
    "sajda": 0,
    "ayah": 78,
  },
  "56": {
    "arabic": "الواقعة",
    "latin": "Al-Waqia",
    "english": "The Event",
    "location": "The Inevitable",
    "sajda": 1,
    "ayah": 96,
  },
  "57": {
    "arabic": "الحديد",
    "latin": "Al-Hadid",
    "english": "The Iron",
    "location": 2,
    "sajda": 0,
    "ayah": 29,
  },
  "58": {
    "arabic": "المجادلة",
    "latin": "Al-Mujadila",
    "english": "She That Disputes",
    "location": 2,
    "sajda": 0,
    "ayah": 22,
  },
  "59": {
    "arabic": "الحشر",
    "latin": "Al-Hashr",
    "english": "Exile",
    "location": 2,
    "sajda": 0,
    "ayah": 24,
  },
  "60": {
    "arabic": "الممتحنة",
    "latin": "Al-Mumtahina",
    "english": "She That Is to Be Examined",
    "location": 2,
    "sajda": 0,
    "ayah": 13,
  },
  "61": {
    "arabic": "الصف",
    "latin": "As-Saff",
    "english": "The Ranks",
    "location": 2,
    "sajda": 0,
    "ayah": 14,
  },
  "62": {
    "arabic": "الجمعة",
    "latin": "Al-Jumua",
    "english": "The Congregation",
    "location": "Friday",
    "sajda": 2,
    "ayah": 11,
  },
  "63": {
    "arabic": "المنافقون",
    "latin": "Al-Munafiqoon",
    "english": "The Hypocrites",
    "location": 2,
    "sajda": 0,
    "ayah": 11,
  },
  "64": {
    "arabic": "التغابن",
    "latin": "At-Taghabun",
    "english": "Mutual Disillusion",
    "location": 2,
    "sajda": 0,
    "ayah": 18,
  },
  "65": {
    "arabic": "الطلاق",
    "latin": "At-Talaq",
    "english": "Divorce",
    "location": 2,
    "sajda": 0,
    "ayah": 12,
  },
  "66": {
    "arabic": "التحريم",
    "latin": "At-Tahrim",
    "english": "Banning",
    "location": 2,
    "sajda": 0,
    "ayah": 12,
  },
  "67": {
    "arabic": "الملك",
    "latin": "Al-Mulk",
    "english": "The Sovereignty",
    "location": 1,
    "sajda": 0,
    "ayah": 30,
  },
  "68": {
    "arabic": "القلم",
    "latin": "Al-Qalam",
    "english": "The Pen",
    "location": 1,
    "sajda": 0,
    "ayah": 52,
  },
  "69": {
    "arabic": "الحاقة",
    "latin": "Al-Haaqqa",
    "english": "The Reality",
    "location": 1,
    "sajda": 0,
    "ayah": 52,
  },
  "70": {
    "arabic": "المعارج",
    "latin": "Al-Maarij",
    "english": "The Ascending Stairways",
    "location": 1,
    "sajda": 0,
    "ayah": 44,
  },
  "71": {
    "arabic": "نوح",
    "latin": "Nooh",
    "english": "Nooh",
    "location": 1,
    "sajda": 0,
    "ayah": 28,
  },
  "72": {
    "arabic": "الجن",
    "latin": "Al-Jinn",
    "english": "The Jinn",
    "location": 1,
    "sajda": 0,
    "ayah": 28,
  },
  "73": {
    "arabic": "المزمل",
    "latin": "Al-Muzzammil",
    "english": "The Enshrouded One",
    "location": 1,
    "sajda": 0,
    "ayah": 20,
  },
  "74": {
    "arabic": "المدثر",
    "latin": "Al-Muddathir",
    "english": "The Cloaked One",
    "location": 1,
    "sajda": 0,
    "ayah": 56,
  },
  "75": {
    "arabic": "القيامة",
    "latin": "Al-Qiyama",
    "english": "The Rising of the Dead",
    "location": 1,
    "sajda": 0,
    "ayah": 40,
  },
  "76": {
    "arabic": "الإنسان",
    "latin": "Al-Insan",
    "english": "The Man",
    "location": 2,
    "sajda": 0,
    "ayah": 31,
  },
  "77": {
    "arabic": "المرسلات",
    "latin": "Al-Mursalat",
    "english": "The Emissaries",
    "location": 1,
    "sajda": 0,
    "ayah": 50,
  },
  "78": {
    "arabic": "النبأ",
    "latin": "An-Naba",
    "english": "The Tidings",
    "location": 1,
    "sajda": 0,
    "ayah": 40,
  },
  "79": {
    "arabic": "النازعات",
    "latin": "An-Naziat",
    "english": "Those Who Drag Forth",
    "location": 1,
    "sajda": 0,
    "ayah": 46,
  },
  "80": {
    "arabic": "عبس",
    "latin": "Abasa",
    "english": "He Frowned",
    "location": 1,
    "sajda": 0,
    "ayah": 42,
  },
  "81": {
    "arabic": "التكوير",
    "latin": "At-Takwir",
    "english": "The Overthrowing",
    "location": 1,
    "sajda": 0,
    "ayah": 29,
  },
  "82": {
    "arabic": "الإنفطار",
    "latin": "AL-Infitar",
    "english": "The Cleaving",
    "location": 1,
    "sajda": 0,
    "ayah": 19,
  },
  "83": {
    "arabic": "المطففين",
    "latin": "Al-Mutaffifin",
    "english": "Defrauding",
    "location": 1,
    "sajda": 0,
    "ayah": 36,
  },
  "84": {
    "arabic": "الانشقاق",
    "latin": "Al-Inshiqaq",
    "english": "The Sundering",
    "location": "Splitting Open",
    "sajda": 1,
    "ayah": 21,
  },
  "85": {
    "arabic": "البروج",
    "latin": "Al-Burooj",
    "english": "The Mansions of the Stars",
    "location": 1,
    "sajda": 0,
    "ayah": 22,
  },
  "86": {
    "arabic": "الطارق",
    "latin": "At-Tariq",
    "english": "The Morning Star",
    "location": 1,
    "sajda": 0,
    "ayah": 17,
  },
  "87": {
    "arabic": "الأعلى",
    "latin": "Al-Ala",
    "english": "The Most High",
    "location": 1,
    "sajda": 0,
    "ayah": 19,
  },
  "88": {
    "arabic": "الغاشية",
    "latin": "Al-Ghashiya",
    "english": "The Overwhelming",
    "location": 1,
    "sajda": 0,
    "ayah": 26,
  },
  "89": {
    "arabic": "الفجر",
    "latin": "Al-Fajr",
    "english": "The Dawn",
    "location": 1,
    "sajda": 0,
    "ayah": 30,
  },
  "90": {
    "arabic": "البلد",
    "latin": "Al-Balad",
    "english": "The City",
    "location": 1,
    "sajda": 0,
    "ayah": 20,
  },
  "91": {
    "arabic": "الشمس",
    "latin": "Ash-Shams",
    "english": "The Sun",
    "location": 1,
    "sajda": 0,
    "ayah": 15,
  },
  "92": {
    "arabic": "الليل",
    "latin": "Al-Lail",
    "english": "The Night",
    "location": 1,
    "sajda": 0,
    "ayah": 21,
  },
  "93": {
    "arabic": "الضحى",
    "latin": "Ad-Dhuha",
    "english": "The Morning Hours",
    "location": 1,
    "sajda": 0,
    "ayah": 11,
  },
  "94": {
    "arabic": "الشرح",
    "latin": "Al-Inshirah",
    "english": "Solace",
    "location": 1,
    "sajda": 0,
    "ayah": 8,
  },
  "95": {
    "arabic": "التين",
    "latin": "At-Tin",
    "english": "The Fig",
    "location": 1,
    "sajda": 0,
    "ayah": 8,
  },
  "96": {
    "arabic": "العلق",
    "latin": "Al-Alaq",
    "english": "The Clot",
    "location": 1,
    "sajda": 19,
    "ayah": 19,
  },
  "97": {
    "arabic": "القدر",
    "latin": "Al-Qadr",
    "english": "The Power",
    "location": 1,
    "sajda": 0,
    "ayah": 5,
  },
  "98": {
    "arabic": "البينة",
    "latin": "Al-Bayyina",
    "english": "The Clear proof",
    "location": 2,
    "sajda": 0,
    "ayah": 8,
  },
  "99": {
    "arabic": "الزلزلة",
    "latin": "Al-Zalzala",
    "english": "The Earthquake",
    "location": 2,
    "sajda": 0,
    "ayah": 8,
  },
  "100": {
    "arabic": "العاديات",
    "latin": "Al-Adiyat",
    "english": "The Chargers",
    "location": 1,
    "sajda": 0,
    "ayah": 11,
  },
  "101": {
    "arabic": "القارعة",
    "latin": "Al-Qaria",
    "english": "The Calamity",
    "location": 1,
    "sajda": 0,
    "ayah": 11,
  },
  "102": {
    "arabic": "التكاثر",
    "latin": "At-Takathur",
    "english": "Competition",
    "location": 1,
    "sajda": 0,
    "ayah": 8,
  },
  "103": {
    "arabic": "العصر",
    "latin": "Al-Asr",
    "english": "The declining day",
    "location": 1,
    "sajda": 0,
    "ayah": 3,
  },
  "104": {
    "arabic": "الهمزة",
    "latin": "Al-Humaza",
    "english": "The Traducer",
    "location": 1,
    "sajda": 0,
    "ayah": 9,
  },
  "105": {
    "arabic": "الفيل",
    "latin": "Al-fil",
    "english": "The Elephant",
    "location": 1,
    "sajda": 0,
    "ayah": 5,
  },
  "106": {
    "arabic": "قريش",
    "latin": "Quraish",
    "english": "Quraish",
    "location": 1,
    "sajda": 0,
    "ayah": 4,
  },
  "107": {
    "arabic": "الماعون",
    "latin": "Al-Maun",
    "english": "Alms Giving",
    "location": 1,
    "sajda": 0,
    "ayah": 7,
  },
  "108": {
    "arabic": "الكوثر",
    "latin": "Al-Kauther",
    "english": "Abundance",
    "location": 1,
    "sajda": 0,
    "ayah": 3,
  },
  "109": {
    "arabic": "الكافرون",
    "latin": "Al-Kafiroon",
    "english": "The Disbelievers",
    "location": 1,
    "sajda": 0,
    "ayah": 6,
  },
  "110": {
    "arabic": "النصر",
    "latin": "An-Nasr",
    "english": "The Succour",
    "location": 2,
    "sajda": 0,
    "ayah": 3,
  },
  "111": {
    "arabic": "المسد",
    "latin": "Al-Masadd",
    "english": "The Flame",
    "location": 1,
    "sajda": 0,
    "ayah": 5,
  },
  "112": {
    "arabic": "الإخلاص",
    "latin": "Al-Ikhlas",
    "english": "Absoluteness",
    "location": 1,
    "sajda": 0,
    "ayah": 4,
  },
  "113": {
    "arabic": "الفلق",
    "latin": "Al-Falaq",
    "english": "The Day Break",
    "location": 1,
    "sajda": 0,
    "ayah": 5,
  },
  "114": {
    "arabic": "الناس",
    "latin": "An-Nas",
    "english": "The Mankind",
    "location": 1,
    "sajda": 0,
    "ayah": 6,
  },
}


export default surahs;
